[build]
  command = "npm run build"
  functions = "lambda"
  publish = "public"
[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200